/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1f031cd9-fd6b-48a5-a1e5-44081bdebee3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IMBRMSBt9",
    "aws_user_pools_web_client_id": "5umctqrrp6q5ka96f48uj22c1s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://n3v5hcg2hffchjvt2ujsiuhrvm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-org746taircblb46getlkcyzpu",
    "aws_user_files_s3_bucket": "lingolingorecordings100910-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
